stages:
  - build
  - test
  - deploy

image: docker:20.10.16
services:
  - docker:20.10.16-dind

variables:
  DOCKER_DRIVER: overlay2
  CI_REGISTRY: registry.gitlab.com

build:
  stage: build
  only:
    - main
  script:
    - echo "Building Docker image..."
    - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASSWORD" $CI_REGISTRY
    - docker build -t "$CI_REGISTRY_IMAGE:latest" .
    - docker push "$CI_REGISTRY_IMAGE:latest"

test:
  stage: test
  only:
    - main
  image: node:18
  script:
    - npm install
    - npm test

deploy:
  stage: deploy
  only:
    - main
  environment:
    name: production
  image: alpine:latest
  before_script:
    - apk add --no-cache openssh-client
    - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - mkdir -p ~/.ssh
    - echo -e "Host $SSH_HOST\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
  script:
    - echo "Deploying to EC2..."
    - scp -i ~/.ssh/id_rsa docker-compose.yml $SSH_USER@$SSH_HOST:/home/ubuntu/app/docker-compose.yml
    - ssh -i ~/.ssh/id_rsa $SSH_USER@$SSH_HOST "cd /home/ubuntu/app && docker pull $CI_REGISTRY_IMAGE:latest && docker compose down && docker compose up -d"
  when: on_success

