services:
  web:
    image: registry.gitlab.com/it-works-on-my-machine1/hello-world:latest
    container_name: hello-web
    ports:
      - "80:3000"
    environment:
      - PORT=3000
    networks:
      - hello-net
    volumes:
      - app-logs:/app/logs

networks:
  hello-net:
    driver: bridge

volumes:
  app-logs:
